### ISSUE TITLE
Which version of node ? Windows support ?

### ISSUE THREAD

**Issue by dbpieter** [Szpadel/chrome-headless-render-pdf#2]
Hi

This seems like a great tool.
Trying it out on windows a.t.m. Unfortunately it explodes right into my face when running a small example.
`const RenderPDF = require('chrome-headless-render-pdf');
RenderPDF.generateSinglePdf('http://google.com', 'outputPdf.pdf');
`

![image](https://user-images.githubusercontent.com/1613011/27306108-a83c6f38-5544-11e7-8934-fa32b5624e71.png)

Running node v7.2.1.

Any help ?

**Comment by Szpadel** [comment]
Published version was compatible 7.6.0, but I published updated version (1.1.5) that should be also compatible with older versions, can you check that?
For windows you will probably have also to specify chrome binary location manually, because I think chrome detection on windows is currently broken.
